// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeFNft4p-Du7ck557oEwot73p_8Zz-IKk',
    appId: '1:801934231614:web:ac83f4106fe9a4cd2e696f',
    messagingSenderId: '801934231614',
    projectId: 'beta-d8322',
    authDomain: 'beta-d8322.firebaseapp.com',
    storageBucket: 'beta-d8322.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDJjuwN8YmmFoCjlx2DY_p-uHFEEq2_ZU',
    appId: '1:801934231614:android:fc046d4a4c5ddf9c2e696f',
    messagingSenderId: '801934231614',
    projectId: 'beta-d8322',
    storageBucket: 'beta-d8322.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCBUGOxE5KpNeT1W2wecYBO25KXF16rfI',
    appId: '1:801934231614:ios:728e2376c15712fd2e696f',
    messagingSenderId: '801934231614',
    projectId: 'beta-d8322',
    storageBucket: 'beta-d8322.appspot.com',
    iosBundleId: 'com.example.beta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCBUGOxE5KpNeT1W2wecYBO25KXF16rfI',
    appId: '1:801934231614:ios:32071a00f79df5e52e696f',
    messagingSenderId: '801934231614',
    projectId: 'beta-d8322',
    storageBucket: 'beta-d8322.appspot.com',
    iosBundleId: 'com.example.beta.RunnerTests',
  );
}
